[package]
name = "rust_ftp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.4.0"
tokio-core = "0.1.18"
tokio-io = "0.1.13"
futures = "0.3.26"